# Generated by Django 4.0.1 on 2022-12-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
    ]
